version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NODE_ENV=production
    env_file:
      - .env